sudo: required
dist: trusty

language:
  - node_js

node_js:
  - node

services:
  - postgresql

before_script:
  - psql -c 'create database testdb;' -U postgres

script:
  - npm run test-travis

after_success:
- npm run coveralls
