// user
// export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
// export const CREATE_USER = 'CREATE_USER';
// export const CURRENT_USER = 'CURRENT_USER';
// export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
// export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';

export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const SIGNUP_SUCCESSFUL = 'SIGNUP_SUCCESSFUL';